function htmlFormatter(str) {
    return (str
        .replace(/\bArray(?=\.)/g, `<span class="green">Array</span>`)
        .replace(/(?<=\.)from(?=\()/g, `<span class="yellow">from</span>`)
        .replace(/(?<=\.)keys(?=\()/g, `<span class="yellow">keys</span>`)
        .replace(/(?<=\.)sort(?=\()/g, `<span class="yellow">sort</span>`)
        .replace(/(?<=\.)localeCompare(?=\()/g, `<span class="yellow">localeCompare</span>`) 
        .replace(/\blet\b/g, `<span class="blue">let</span>`)
        .replace(/\bfor(?=\()/g, `<span class="purple">for</span>`)
        .replace(/(?<=\()const\b/g, `<span class="blue">const</span>`)
        .replace(/\bof\b/g, `<span class="blue">of</span>`)
        .replace(/\bconsole(?=\.)/g, `<span class="green">console</span>`)
        .replace(/(?<=\.)log(?=\()/g, `<span class="yellow">log</span>`)
        .replace(/(?<=\.)get(?=\()/g, `<span class="yellow">get</span>`)
        .replace(/(?<=\s{1})=>(?=\s{1})/g, `<span class="blue">=></span>`)
        .replace(/\bif(?=\s\()/g, `<span class="purple">if</span>`)
        .replace(/\breturn\b/g, `<span class="purple">return</span>`)
        .replace(/\b\d+(?=\)|\s)/g, x => `<span class="olive">${x}</span>`)
        .replace(/(?<=<\/span>.|-\s|=\s)[a-zA-Z]+|\w+(?= ===)/g, x => `<span class="lblue">${x}</span>`)
    )
}
//console.log(htmlFormatter('return 0'))